### ISSUE TITLE
Does not appear in Rack 0.6.0

### ISSUE THREAD

**Issue by caecos** [starlingcode/Via-for-Rack#10]
The sources compile correctly but once in the plugins folder does not appear in the rolldown menu!?

**Comment by liquidcitymotors** [comment]
Hi, thanks for letting us know. I am not able to replicate this on macOS and Rack 0.6.0. The plugin should be listed under the temporary manufacturer identifier "CompanyName". You are able to generate a ZIP package with "make dist"? What is your build system?

**Comment by caecos** [comment]
Hi,

Exact, the module show off Under CompanyName…and it works fine.

Regards,

Marc

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : Will Mitchell <notifications@github.com>
Envoyé : Thursday, May 31, 2018 10:34:22 PM
À : liquidcitymotors/Via-for-VCVRack
Cc : caecos; Author
Objet : Re: [liquidcitymotors/Via-for-VCVRack] Does not appear in Rack 0.6.0 (#10)


Hi, thanks for letting us know. I am not able to replicate this on macOS and Rack 0.6.0. The plugin should be listed under the temporary manufacturer identifier "CompanyName". You are able to generate a ZIP package with "make dist"? What is your build system?

**Comment by liquidcitymotors** [comment]
closing stale issues
