### ISSUE TITLE
git submodule error

### ISSUE THREAD

**Issue by 573** [starlingcode/Via-for-Rack#11]
vcvrack sources v0.6
Via sources master (89e1cd96bab7a1cf9107e31eb4eebbb75da3a502)

Hi I am getting this weird error:  

> rack_plugins_1      | ++ git submodule update --init --recursive
rack_plugins_1      | Submodule 'Via' (https://github.com/liquidcitymotors/Via) registered for path 'Via'
rack_plugins_1      | Cloning into 'Via'...
rack_plugins_1      | fatal: reference is not a tree: 640ddf118c0314f19ca03797682aaa0f278cc7f4
rack_plugins_1      | Unable to checkout '640ddf118c0314f19ca03797682aaa0f278cc7f4' in submodule path 'Via'
vcvrackdocker_rack_plugins_1 exited with code 1

**Comment by liquidcitymotors** [comment]
@573 Thanks for this. Looks like I forgot to push a commit. The submodule should clone just fine now. Let me know if you run into any other build problems! Heads up, this is still probably still a bit buggy because its still being developed.

**Comment by liquidcitymotors** [comment]
Closing neglected issues
