### ISSUE TITLE
Plugin occasionally crashing Rack under Windows

### ISSUE THREAD

**Issue by dizzisound** [starlingcode/Via-for-Rack#4]
OS: Windows 7/8.1 
Using compiled version as is. I could load the module and play with it most of the time.
Upon being notified by another Win 7 user that the compiled plugin crashed Rack on his Windows 7 system, I tried some destructive testing. I manage to replicate a runtime memory exception, in particular when I repeatedly keep to trigger the arrow-up (wavetable bank toggle) and the FREQ button, with quick and alternate clicks.
I attach screenshots from Visual Studio and Windows Event log viewer.

![vcvia-crash-debugger](https://user-images.githubusercontent.com/36040812/37163446-19f939f4-22f8-11e8-82db-c5d103d95e52.png)

![vcvia-crash-syslog](https://user-images.githubusercontent.com/36040812/37163460-1ffebf7c-22f8-11e8-8dbf-a761ae6eec29.png)

**Comment by liquidcitymotors** [comment]
Thank you so much for the detail, and for building under Windows. I've been caught up in finalizing the hardware VIA and have been neglecting developing the VCV Rack version. Your report confirms a suspicion that the wavetable data structure is unstable. This makes sense because I shoehorned code written for an embedded system into an object oriented system :^/ 
It's a bit of a task that might take a while, but I will report back when I have implemented a more robust way of storing wavetable data. Disclaimer, this module is my first software development project, so I am in somewhat uncharted waters.

**Comment by dizzisound** [comment]
@liquidcitymotors First of all, thanks for your reply. I have to confirm that personally I manage to load and successfully play with the module most of the time, and it's lot of fun and great quality. I really wish you to find your way through the robustness issue, in the time it will take, because I think your work absolutely deserves a public release! 
You find me available for every support in compiling, testing or reporting on the Windows platform.

**Comment by liquidcitymotors** [comment]
@dizzisound I did confirm this with the version you were testing. Some data management changes and a fixed bug in playback should alleviate this problem in the most recent commit. Note that the plugin has been updated for compatibility with the 0.6 version of Rack.

**Comment by dizzisound** [comment]
@liquidcitymotors I think I'm going to build it as soon as I can, and have some fun! Thank you for the notification.

**Comment by dizzisound** [comment]
@liquidcitymotors FYI, just compiled against last master sources of Rack, still a few warnings concerning mainly some deprecated helper functions (createParam, createLight, etc.), but the build completed successfully. After loading into Rack and playing with the module, I can confirm you that I couldn't replicate the memory access violation. Nice work!

**Comment by liquidcitymotors** [comment]
Thanks again @dizzisound. You might have some fun with the changes to the UI and wavetable playback engine in the most recent commits. I did change around the code that was causing problems for us before, so before I close this I want to make sure my changes didn't break anything.

**Comment by liquidcitymotors** [comment]
closing stale issues
